#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AWSBetting.Resource", IsApplication=true)]

namespace AWSBetting
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::AWSBetting.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::AWSBetting.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::AWSBetting.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::AWSBetting.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_content_create = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_save = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_delete_sweep_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_delete_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_copy_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_cut_holo_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_paste_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_search_holo_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_monetization_on_white_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_settings_white_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int profit = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int ActiveBetList = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int Calculate = 2131099666;
			
			// aapt resource value: 0x7f06001e
			public const int ClosedBetList = 2131099678;
			
			// aapt resource value: 0x7f06000e
			public const int History = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int NextBet = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int Offset = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int Profit = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int Quote = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int SaveBet = 2131099671;
			
			// aapt resource value: 0x7f060006
			public const int activeBet = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int activeBetHeader = 2131099649;
			
			// aapt resource value: 0x7f06001b
			public const int activeTeamsSpinner = 2131099675;
			
			// aapt resource value: 0x7f06000b
			public const int addBetBtn = 2131099659;
			
			// aapt resource value: 0x7f060027
			public const int balanceLayout = 2131099687;
			
			// aapt resource value: 0x7f06002e
			public const int betProviders = 2131099694;
			
			// aapt resource value: 0x7f060009
			public const int betType = 2131099657;
			
			// aapt resource value: 0x7f060019
			public const int calendarLeagueSpinner = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int calendarsView = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int closeBetDialog = 2131099674;
			
			// aapt resource value: 0x7f060024
			public const int closedBet = 2131099684;
			
			// aapt resource value: 0x7f06001f
			public const int closedBetHeader = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int closedBetRow = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int closedBetTeam = 2131099683;
			
			// aapt resource value: 0x7f060020
			public const int closedTeamHeader = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int closedWinHeader = 2131099681;
			
			// aapt resource value: 0x7f06000c
			public const int digitalClock1 = 2131099660;
			
			// aapt resource value: 0x7f060026
			public const int edit_toolbar = 2131099686;
			
			// aapt resource value: 0x7f06000a
			public const int firstBet = 2131099658;
			
			// aapt resource value: 0x7f060029
			public const int frameLayout1 = 2131099689;
			
			// aapt resource value: 0x7f060025
			public const int home = 2131099685;
			
			// aapt resource value: 0x7f060007
			public const int lastBet = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int lastBetHeader = 2131099651;
			
			// aapt resource value: 0x7f060030
			public const int leagueSpinner = 2131099696;
			
			// aapt resource value: 0x7f060033
			public const int menu_close = 2131099699;
			
			// aapt resource value: 0x7f060031
			public const int menu_create = 2131099697;
			
			// aapt resource value: 0x7f060036
			public const int menu_delete = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int menu_deleteAll = 2131099703;
			
			// aapt resource value: 0x7f060032
			public const int menu_edit = 2131099698;
			
			// aapt resource value: 0x7f060034
			public const int menu_preferences = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int menu_save = 2131099701;
			
			// aapt resource value: 0x7f06002c
			public const int modBetType = 2131099692;
			
			// aapt resource value: 0x7f06002b
			public const int modLastBet = 2131099691;
			
			// aapt resource value: 0x7f06002a
			public const int modTeamName = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int modifyBetToolbar = 2131099693;
			
			// aapt resource value: 0x7f060028
			public const int plot_view = 2131099688;
			
			// aapt resource value: 0x7f06002f
			public const int rankingsView = 2131099695;
			
			// aapt resource value: 0x7f060004
			public const int relativeLayout1 = 2131099652;
			
			// aapt resource value: 0x7f06001d
			public const int saveWin = 2131099677;
			
			// aapt resource value: 0x7f060005
			public const int team = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int teamHeader = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int teamName = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int textView1 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int textView2 = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int textView3 = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int textView4 = 2131099669;
			
			// aapt resource value: 0x7f06001c
			public const int win = 2131099676;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActiveBet = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActiveBetHeader = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ActiveBetRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AddBet = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BettingTitleBar = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CalculateBet = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Calendar = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int CloseBetDialog = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ClosedBet = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ClosedBetHeader = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ClosedBetRow = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Home = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ModifyBet = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ProviderChoiceDialog = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Rankings = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int edit_menus = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int modifyBet_menus = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ActiveBet_Tab_Label = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int Calendars_Tab_Label = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int ClosedBet_Tab_Label = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Home_Tab_Label = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int Rankings_Tab_Label = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int teams_prompt = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
